# Plugins
plugins:
  - jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mikhail Budnikov
url:              http://msh2481.github.io/
baseurl:          /

paginate:         5